### ISSUE TITLE
Question about the oMO

### ISSUE THREAD

**Issue by Sanarmy** [grimme-lab/stda#22]
I'm triying to use DFT-STDA, the DFT calculation of ground state are performed in GAUSSIAN 16 (following all the parameters for the molden input file are needed following the manual of STDA), and here i obtain 94 electrons for the anthracene molecule. Then as the STDA instructions says i create a molden input file with g2molden and run the calculations, but when i see the resulst, the STDA program says that i have 26 occupied molecular orbitals instead of 47. But for example, in the same molecule using XTB in ground state obtaining 66 electrons, in the STDA calculation i have the rigth number of occupied molecular orbitals (33). 
Why is this happening, Have i consider something else in Gaussian?

**Comment by cbannwarth** [comment]
what energy threshold did you use `(-e)`? sTDA selects the relevant orbitals beforehand based on the energy threshold, starting from the HOMO & LUMO. Probably there are fewer occupied orbitals within that energy threshold that you selected. 
Does the number go up, if you pick a larger `e` value?

**Comment by Sanarmy** [comment]
Okey the number goes up using a higher -e, now I'm using -e 20 and it prints me now 33 occupied molecular orbitals, but when i chose for exmaple -e 25, a warning appears: internal MO norm error. Other question is, if the STDA recalculate the number of electrons taking account only the valence ones?

**Comment by cbannwarth** [comment]
are you using `-sty 3` or have you run with `-chk` first?

**Comment by Sanarmy** [comment]
I'm using -sty 3

**Comment by cbannwarth** [comment]
ok, I have only experienced this for larger molecules before and this is the case for the MO normthreshold being tighter than the number of significant digits printed in the Gaussian output

**Comment by cbannwarth** [comment]
But no, sTDA does not select only valence orbitals

**Comment by Sanarmy** [comment]
I notice that in B3LYP with small basis as STO-3G or 3-21G it works, it prints me the 47 occupied MO with a high trheshold of -e (more than 40). But when i used higher basis as 6-31G and 6-31G** the highest -e that i can use is around 20, because up to 25 it appears the error (internal MO norm error) and only prints me 33 occupied MO instead of the 47. There is anything that i can do to solve this?

**Comment by mdewergi** [comment]
Can you provide us a molden file to do some tests on it? Because this is unusual. I know that the integral deck is not always sturdy and will be replaced in the next version of stda by the libcint library. So I know cases that MO norm error is solved by just switching integral decks. But I have never seen that behavior with stda when increasing the threshold. By the way, it is counterproductive to use such large threshold with stda because you will loose the efficiency and also add high energy CSFs that are probably not so well described by the monopole approximation for integrals.

**Comment by Sanarmy** [comment]
Here i attach you the two molden files of anthracene calculated with B3LYP/6-31G and 6-31G** in Gaussian 16.
[anthracene_stda.zip](https://github.com/grimme-lab/stda/files/14599826/anthracene_stda.zip)

**Comment by mdewergi** [comment]
The problem is  molden files that have not enough digits. I have tried with qchem the same ground state calculation and used it with stda and everything works fine. Unfortunately, we cannot do anything about it. If you have access to gaussian sources you can edit the subroutine that writes the molden file and change the print format of LCAO coefficients to double float. 

Attached you have anthracene molden file with 6-31G** generated with qchem. 
[molden.zip](https://github.com/grimme-lab/stda/files/14600187/molden.zip)

Best wishes,
Marc

**Comment by Sanarmy** [comment]
Okey, perfect. Thank you !!
